main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Index:index }

skills_page:
    path:     /competences/
    defaults: { _controller: MainBundle:Index:skills }

skills_page_old:
    path:     /mes-competences-en-informatique.html
    defaults: { _controller: MainBundle:Index:skills }
